version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/phone_scheduler
      - DEBUG=True
      - LOG_LEVEL=INFO
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 